name: vote CI/CD

# Exclude the workflow to run on changes to the helm chart
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:

  # Build and Test Python app
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r vote/requirements.txt
        pip install pytest    

    - name: Run tests
      run: |
        cd vote && pytest 

  # Run code quality check using flake8
  code-quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install flake8
      run: pip install flake8

    - name: Run flake8 linting
      run: flake8 vote

  # Build and Push Docker Image
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        context: ./vote
        file: ./vote/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/vote-app:${{github.run_id}}

  # Update the Helm chart with the new Docker image tag
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest

    needs: push

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}

    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/vote-app-chart/vote/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "varshil@gmail.com"
        git config --global user.name "Varshil Desai"
        git add helm/vote-app-chart/vote/values.yaml
        git commit -m "Update vote tag in Helm chart"
        git push
